// Code generated by thriftgo (0.3.6). DO NOT EDIT.

package models

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
)

type CpsType int64

const (
	CpsType_Unknow CpsType = 0
)

func (p CpsType) String() string {
	switch p {
	case CpsType_Unknow:
		return "Unknow"
	}
	return "<UNSET>"
}

func CpsTypeFromString(s string) (CpsType, error) {
	switch s {
	case "Unknow":
		return CpsType_Unknow, nil
	}
	return CpsType(0), fmt.Errorf("not a valid CpsType string")
}

func CpsTypePtr(v CpsType) *CpsType { return &v }
func (p *CpsType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = CpsType(result.Int64)
	return
}

func (p *CpsType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type CpsRebateDiscounts struct {
	ID       *string  `thrift:"id,1,optional" form:"id" json:"id,omitempty" query:"id"`
	AppID    *string  `thrift:"app_id,2,optional" form:"app_id" json:"app_id,omitempty" query:"app_id"`
	Name     *string  `thrift:"name,3,optional" form:"name" json:"name,omitempty" query:"name"`
	CpsType  *CpsType `thrift:"cps_type,4,optional" form:"cps_type" json:"cps_type,omitempty" query:"cps_type"`
	JumpLink *string  `thrift:"jump_link,5,optional" form:"jump_link" json:"jump_link,omitempty" query:"jump_link"`
	Extra    *string  `thrift:"extra,6,optional" form:"extra" json:"extra,omitempty" query:"extra"`
	Status   *int32   `thrift:"status,7,optional" form:"status" json:"status,omitempty" query:"status"`
}

func NewCpsRebateDiscounts() *CpsRebateDiscounts {
	return &CpsRebateDiscounts{}
}

var CpsRebateDiscounts_ID_DEFAULT string

func (p *CpsRebateDiscounts) GetID() (v string) {
	if !p.IsSetID() {
		return CpsRebateDiscounts_ID_DEFAULT
	}
	return *p.ID
}

var CpsRebateDiscounts_AppID_DEFAULT string

func (p *CpsRebateDiscounts) GetAppID() (v string) {
	if !p.IsSetAppID() {
		return CpsRebateDiscounts_AppID_DEFAULT
	}
	return *p.AppID
}

var CpsRebateDiscounts_Name_DEFAULT string

func (p *CpsRebateDiscounts) GetName() (v string) {
	if !p.IsSetName() {
		return CpsRebateDiscounts_Name_DEFAULT
	}
	return *p.Name
}

var CpsRebateDiscounts_CpsType_DEFAULT CpsType

func (p *CpsRebateDiscounts) GetCpsType() (v CpsType) {
	if !p.IsSetCpsType() {
		return CpsRebateDiscounts_CpsType_DEFAULT
	}
	return *p.CpsType
}

var CpsRebateDiscounts_JumpLink_DEFAULT string

func (p *CpsRebateDiscounts) GetJumpLink() (v string) {
	if !p.IsSetJumpLink() {
		return CpsRebateDiscounts_JumpLink_DEFAULT
	}
	return *p.JumpLink
}

var CpsRebateDiscounts_Extra_DEFAULT string

func (p *CpsRebateDiscounts) GetExtra() (v string) {
	if !p.IsSetExtra() {
		return CpsRebateDiscounts_Extra_DEFAULT
	}
	return *p.Extra
}

var CpsRebateDiscounts_Status_DEFAULT int32

func (p *CpsRebateDiscounts) GetStatus() (v int32) {
	if !p.IsSetStatus() {
		return CpsRebateDiscounts_Status_DEFAULT
	}
	return *p.Status
}

var fieldIDToName_CpsRebateDiscounts = map[int16]string{
	1: "id",
	2: "app_id",
	3: "name",
	4: "cps_type",
	5: "jump_link",
	6: "extra",
	7: "status",
}

func (p *CpsRebateDiscounts) IsSetID() bool {
	return p.ID != nil
}

func (p *CpsRebateDiscounts) IsSetAppID() bool {
	return p.AppID != nil
}

func (p *CpsRebateDiscounts) IsSetName() bool {
	return p.Name != nil
}

func (p *CpsRebateDiscounts) IsSetCpsType() bool {
	return p.CpsType != nil
}

func (p *CpsRebateDiscounts) IsSetJumpLink() bool {
	return p.JumpLink != nil
}

func (p *CpsRebateDiscounts) IsSetExtra() bool {
	return p.Extra != nil
}

func (p *CpsRebateDiscounts) IsSetStatus() bool {
	return p.Status != nil
}

func (p *CpsRebateDiscounts) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField2(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField3(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 4:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField4(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField5(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 6:
			if fieldTypeId == thrift.STRING {
				if err = p.ReadField6(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		case 7:
			if fieldTypeId == thrift.I32 {
				if err = p.ReadField7(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_CpsRebateDiscounts[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *CpsRebateDiscounts) ReadField1(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.ID = &v
	}
	return nil
}
func (p *CpsRebateDiscounts) ReadField2(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.AppID = &v
	}
	return nil
}
func (p *CpsRebateDiscounts) ReadField3(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Name = &v
	}
	return nil
}
func (p *CpsRebateDiscounts) ReadField4(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		tmp := CpsType(v)
		p.CpsType = &tmp
	}
	return nil
}
func (p *CpsRebateDiscounts) ReadField5(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.JumpLink = &v
	}
	return nil
}
func (p *CpsRebateDiscounts) ReadField6(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadString(); err != nil {
		return err
	} else {
		p.Extra = &v
	}
	return nil
}
func (p *CpsRebateDiscounts) ReadField7(iprot thrift.TProtocol) error {

	if v, err := iprot.ReadI32(); err != nil {
		return err
	} else {
		p.Status = &v
	}
	return nil
}

func (p *CpsRebateDiscounts) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("CpsRebateDiscounts"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
		if err = p.writeField2(oprot); err != nil {
			fieldId = 2
			goto WriteFieldError
		}
		if err = p.writeField3(oprot); err != nil {
			fieldId = 3
			goto WriteFieldError
		}
		if err = p.writeField4(oprot); err != nil {
			fieldId = 4
			goto WriteFieldError
		}
		if err = p.writeField5(oprot); err != nil {
			fieldId = 5
			goto WriteFieldError
		}
		if err = p.writeField6(oprot); err != nil {
			fieldId = 6
			goto WriteFieldError
		}
		if err = p.writeField7(oprot); err != nil {
			fieldId = 7
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *CpsRebateDiscounts) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetID() {
		if err = oprot.WriteFieldBegin("id", thrift.STRING, 1); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.ID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *CpsRebateDiscounts) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetAppID() {
		if err = oprot.WriteFieldBegin("app_id", thrift.STRING, 2); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.AppID); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 2 end error: ", p), err)
}

func (p *CpsRebateDiscounts) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetName() {
		if err = oprot.WriteFieldBegin("name", thrift.STRING, 3); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Name); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 3 end error: ", p), err)
}

func (p *CpsRebateDiscounts) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetCpsType() {
		if err = oprot.WriteFieldBegin("cps_type", thrift.I32, 4); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(int32(*p.CpsType)); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 4 end error: ", p), err)
}

func (p *CpsRebateDiscounts) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetJumpLink() {
		if err = oprot.WriteFieldBegin("jump_link", thrift.STRING, 5); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.JumpLink); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 5 end error: ", p), err)
}

func (p *CpsRebateDiscounts) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetExtra() {
		if err = oprot.WriteFieldBegin("extra", thrift.STRING, 6); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteString(*p.Extra); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 6 end error: ", p), err)
}

func (p *CpsRebateDiscounts) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetStatus() {
		if err = oprot.WriteFieldBegin("status", thrift.I32, 7); err != nil {
			goto WriteFieldBeginError
		}
		if err := oprot.WriteI32(*p.Status); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 7 end error: ", p), err)
}

func (p *CpsRebateDiscounts) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CpsRebateDiscounts(%+v)", *p)

}
