// Code generated by hertz generator.

package howell_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cps_rebate_discountsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcpsrebatediscountsMw() []app.HandlerFunc {
	// your code...
	return nil
}
